[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"

[project]
name = "shoreman"
version = "0.0.1"
dependencies = []

[project.scripts]
shoreman = "shoreman.entry:cli"

[tool.setuptools]
packages = ['shoreman']
